using System;
using System.Drawing;
using System.Windows.Forms;

namespace AppWatchdog.UI
{
    partial class MainForm
    {
        private System.ComponentModel.IContainer components = null;

        private MenuStrip menuStripMain;
        private ToolStripMenuItem menuFile;
        private ToolStripMenuItem menuFileExit;
        private ToolStripMenuItem menuView;
        private ToolStripMenuItem menuViewEventLog;
        private ToolStripMenuItem menuViewOpenLogFolder;
        private ToolStripMenuItem menuHelp;
        private ToolStripMenuItem menuHelpAbout;

        private StatusStrip statusStripMain;
        private ToolStripStatusLabel stService;
        private ToolStripStatusLabel stPipe;
        private ToolStripStatusLabel stDirty;
        private ToolStripStatusLabel stLastSnapshot;

        private TabControl tabControl;
        private TabPage tabService;
        private TabPage tabApps;
        private TabPage tabMail;
        private TabPage tabLogs;

        private GroupBox grpServiceStatus;
        private Label lblServiceStatusLabel;
        private Label lblServiceStatus;
        private Button btnRefreshStatus;
        private Label lblSnapshot;
        private Button btnTriggerCheck;

        private GroupBox grpServiceActions;
        private Button btnInstall;
        private Button btnUninstall;
        private Button btnStart;
        private Button btnStop;
        private Button btnEventLog;

        private GroupBox grpAppsTop;
        private Button btnSaveApps;
        private Button btnReloadApps;
        private Label lblDirtyApps;

        private DataGridView gridApps;

        private Button btnAddApp;
        private Button btnRemoveApp;
        private Button btnBrowseApp;

        private GroupBox grpIntervals;
        private Label lblCheckInterval;
        private NumericUpDown numCheckInterval;
        private Label lblMailInterval;
        private NumericUpDown numMailInterval;

        private GroupBox grpAppsNerd;
        private Label lblAppsNerd;

        private GroupBox grpMailTop;
        private Button btnSaveMail;
        private Button btnReloadMail;
        private Label lblDirtyMail;

        private GroupBox grpMailServer;
        private Label lblSmtpServer;
        private TextBox txtSmtpServer;
        private Label lblSmtpPort;
        private TextBox txtSmtpPort;
        private CheckBox chkSmtpSsl;

        private GroupBox grpMailAuth;
        private Label lblSmtpUser;
        private TextBox txtSmtpUser;
        private Label lblSmtpPass;
        private TextBox txtSmtpPass;

        private GroupBox grpMailAddresses;
        private Label lblMailFrom;
        private TextBox txtMailFrom;
        private Label lblMailTo;
        private TextBox txtMailTo;

        private Button btnTestMail;

        private GroupBox grpMailNerd;
        private Label lblMailNerd;

        private GroupBox grpNtfyTop;
        private Button btnSaveNtfy;
        private Button btnReloadNtfy;
        private Label lblDirtyNtfy;

        private GroupBox grpNtfyServer;
        private Label lblNtfyBaseUrl;
        private TextBox txtNtfyBaseUrl;

        private GroupBox grpNtfyAuth;
        private Label lblNtfyToken;
        private TextBox txtNtfyToken;

        private GroupBox grpNtfyMessage;
        private Label lblNtfyTopic;
        private TextBox txtNtfyTopic;
        private Label lblNtfyTitle;
        private TextBox txtNtfyTitle;
        private Label lblNtfyPriority;
        private ComboBox cmbNtfyPriority;
        private Label lblNtfyTags;
        private TextBox txtNtfyTags;

        private Button btnTestNtfy;

        private GroupBox grpNtfyNerd;
        private Label lblNtfyNerd;

        private GroupBox grpLogsTop;
        private ComboBox cmbLogDate;
        private Button btnReloadLogs;
        private Button btnOpenLogFolder;
        private CheckBox chkAutoScroll;

        private RichTextBox txtLogs;

        private GroupBox grpLogsNerd;
        private Label lblLogsNerd;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null)
                components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            menuStripMain = new MenuStrip();
            menuFile = new ToolStripMenuItem();
            menuFileExit = new ToolStripMenuItem();
            menuHelp = new ToolStripMenuItem();
            menuHelpAbout = new ToolStripMenuItem();
            menuView = new ToolStripMenuItem();
            menuViewEventLog = new ToolStripMenuItem();
            menuViewOpenLogFolder = new ToolStripMenuItem();
            statusStripMain = new StatusStrip();
            stService = new ToolStripStatusLabel();
            stPipe = new ToolStripStatusLabel();
            stDirty = new ToolStripStatusLabel();
            stLastSnapshot = new ToolStripStatusLabel();
            tabControl = new TabControl();
            tabService = new TabPage();
            grpServiceStatus = new GroupBox();
            lblServiceStatusLabel = new Label();
            lblServiceStatus = new Label();
            btnRefreshStatus = new Button();
            lblSnapshot = new Label();
            btnTriggerCheck = new Button();
            grpServiceActions = new GroupBox();
            btnInstall = new Button();
            btnUninstall = new Button();
            btnStart = new Button();
            btnStop = new Button();
            btnEventLog = new Button();
            tabApps = new TabPage();
            grpAppsTop = new GroupBox();
            btnSaveApps = new Button();
            btnReloadApps = new Button();
            lblDirtyApps = new Label();
            gridApps = new DataGridView();
            btnAddApp = new Button();
            btnRemoveApp = new Button();
            btnBrowseApp = new Button();
            grpIntervals = new GroupBox();
            lblCheckInterval = new Label();
            numCheckInterval = new NumericUpDown();
            lblMailInterval = new Label();
            numMailInterval = new NumericUpDown();
            grpAppsNerd = new GroupBox();
            lblAppsNerd = new Label();
            tabMail = new TabPage();
            grpMailTop = new GroupBox();
            btnSaveMail = new Button();
            btnReloadMail = new Button();
            lblDirtyMail = new Label();
            grpMailServer = new GroupBox();
            lblSmtpServer = new Label();
            txtSmtpServer = new TextBox();
            lblSmtpPort = new Label();
            txtSmtpPort = new TextBox();
            chkSmtpSsl = new CheckBox();
            grpMailAuth = new GroupBox();
            lblSmtpUser = new Label();
            txtSmtpUser = new TextBox();
            lblSmtpPass = new Label();
            txtSmtpPass = new TextBox();
            grpMailAddresses = new GroupBox();
            lblMailFrom = new Label();
            txtMailFrom = new TextBox();
            lblMailTo = new Label();
            txtMailTo = new TextBox();
            btnTestMail = new Button();
            grpMailNerd = new GroupBox();
            lblMailNerd = new Label();
            grpNtfyTop = new GroupBox();
            btnSaveNtfy = new Button();
            btnReloadNtfy = new Button();
            lblDirtyNtfy = new Label();
            grpNtfyServer = new GroupBox();
            lblNtfyBaseUrl = new Label();
            txtNtfyBaseUrl = new TextBox();
            grpNtfyAuth = new GroupBox();
            lblNtfyToken = new Label();
            txtNtfyToken = new TextBox();
            grpNtfyMessage = new GroupBox();
            lblNtfyTopic = new Label();
            txtNtfyTopic = new TextBox();
            lblNtfyTitle = new Label();
            txtNtfyTitle = new TextBox();
            lblNtfyPriority = new Label();
            cmbNtfyPriority = new ComboBox();
            lblNtfyTags = new Label();
            txtNtfyTags = new TextBox();
            btnTestNtfy = new Button();
            grpNtfyNerd = new GroupBox();
            lblNtfyNerd = new Label();
            tabLogs = new TabPage();
            grpLogsTop = new GroupBox();
            cmbLogDate = new ComboBox();
            btnReloadLogs = new Button();
            btnOpenLogFolder = new Button();
            chkAutoScroll = new CheckBox();
            txtLogs = new RichTextBox();
            grpLogsNerd = new GroupBox();
            lblLogsNerd = new Label();
            menuStripMain.SuspendLayout();
            statusStripMain.SuspendLayout();
            tabControl.SuspendLayout();
            tabService.SuspendLayout();
            grpServiceStatus.SuspendLayout();
            grpServiceActions.SuspendLayout();
            tabApps.SuspendLayout();
            grpAppsTop.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)gridApps).BeginInit();
            grpIntervals.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)numCheckInterval).BeginInit();
            ((System.ComponentModel.ISupportInitialize)numMailInterval).BeginInit();
            grpAppsNerd.SuspendLayout();
            tabMail.SuspendLayout();
            grpMailTop.SuspendLayout();
            grpMailServer.SuspendLayout();
            grpMailAuth.SuspendLayout();
            grpMailAddresses.SuspendLayout();
            grpMailNerd.SuspendLayout();
            grpNtfyTop.SuspendLayout();
            grpNtfyServer.SuspendLayout();
            grpNtfyAuth.SuspendLayout();
            grpNtfyMessage.SuspendLayout();
            grpNtfyNerd.SuspendLayout();
            tabLogs.SuspendLayout();
            grpLogsTop.SuspendLayout();
            grpLogsNerd.SuspendLayout();
            SuspendLayout();
            menuStripMain.Items.AddRange(new ToolStripItem[] { menuFile, menuHelp, menuView });
            menuStripMain.Location = new Point(0, 0);
            menuStripMain.Name = "menuStripMain";
            menuStripMain.Size = new Size(1100, 24);
            menuStripMain.TabIndex = 0;
            menuFile.DropDownItems.AddRange(new ToolStripItem[] { menuFileExit });
            menuFile.Name = "menuFile";
            menuFile.Size = new Size(46, 20);
            menuFile.Text = "&Datei";
            menuFileExit.Name = "menuFileExit";
            menuFileExit.Size = new Size(120, 22);
            menuFileExit.Text = "Be&enden";
            menuHelp.DropDownItems.AddRange(new ToolStripItem[] { menuHelpAbout });
            menuHelp.Name = "menuHelp";
            menuHelp.Size = new Size(44, 20);
            menuHelp.Text = "&Hilfe";
            menuHelpAbout.Name = "menuHelpAbout";
            menuHelpAbout.Size = new Size(99, 22);
            menuHelpAbout.Text = "Über";
            menuView.DropDownItems.AddRange(new ToolStripItem[] { menuViewEventLog, menuViewOpenLogFolder });
            menuView.Name = "menuView";
            menuView.Size = new Size(59, 20);
            menuView.Text = "&Ansicht";
            menuViewEventLog.Name = "menuViewEventLog";
            menuViewEventLog.Size = new Size(193, 22);
            menuViewEventLog.Text = "Ereignisanzeige öffnen";
            menuViewOpenLogFolder.Name = "menuViewOpenLogFolder";
            menuViewOpenLogFolder.Size = new Size(193, 22);
            menuViewOpenLogFolder.Text = "Log-Ordner öffnen";
            statusStripMain.Items.AddRange(new ToolStripItem[] { stService, stPipe, stDirty, stLastSnapshot });
            statusStripMain.Location = new Point(0, 674);
            statusStripMain.Name = "statusStripMain";
            statusStripMain.Size = new Size(1100, 24);
            statusStripMain.TabIndex = 2;
            stService.BorderSides = ToolStripStatusLabelBorderSides.Right;
            stService.Name = "stService";
            stService.Size = new Size(59, 19);
            stService.Text = "Service: ?";
            stPipe.BorderSides = ToolStripStatusLabelBorderSides.Right;
            stPipe.Name = "stPipe";
            stPipe.Size = new Size(45, 19);
            stPipe.Text = "Pipe: ?";
            stDirty.BorderSides = ToolStripStatusLabelBorderSides.Right;
            stDirty.Name = "stDirty";
            stDirty.Size = new Size(62, 19);
            stDirty.Text = "Config: ✓";
            stLastSnapshot.Name = "stLastSnapshot";
            stLastSnapshot.Size = new Size(67, 19);
            stLastSnapshot.Text = "Snapshot: -";
            tabControl.Controls.Add(tabService);
            tabControl.Controls.Add(tabApps);
            tabControl.Controls.Add(tabMail);
            tabControl.Controls.Add(tabLogs);
            tabControl.Dock = DockStyle.Fill;
            tabControl.Location = new Point(0, 24);
            tabControl.Name = "tabControl";
            tabControl.SelectedIndex = 0;
            tabControl.Size = new Size(1100, 650);
            tabControl.TabIndex = 1;
            tabService.Controls.Add(grpServiceStatus);
            tabService.Controls.Add(grpServiceActions);
            tabService.Location = new Point(4, 24);
            tabService.Name = "tabService";
            tabService.Size = new Size(1092, 622);
            tabService.TabIndex = 0;
            tabService.Text = "Service";
            tabService.UseVisualStyleBackColor = true;
            grpServiceStatus.Controls.Add(lblServiceStatusLabel);
            grpServiceStatus.Controls.Add(lblServiceStatus);
            grpServiceStatus.Controls.Add(btnRefreshStatus);
            grpServiceStatus.Controls.Add(lblSnapshot);
            grpServiceStatus.Controls.Add(btnTriggerCheck);
            grpServiceStatus.Location = new Point(16, 16);
            grpServiceStatus.Name = "grpServiceStatus";
            grpServiceStatus.Size = new Size(1040, 155);
            grpServiceStatus.TabIndex = 0;
            grpServiceStatus.TabStop = false;
            grpServiceStatus.Text = "Status";
            lblServiceStatusLabel.Location = new Point(16, 30);
            lblServiceStatusLabel.Name = "lblServiceStatusLabel";
            lblServiceStatusLabel.Size = new Size(120, 20);
            lblServiceStatusLabel.TabIndex = 0;
            lblServiceStatusLabel.Text = "Service Status:";
            lblServiceStatus.Location = new Point(150, 30);
            lblServiceStatus.Name = "lblServiceStatus";
            lblServiceStatus.Size = new Size(240, 20);
            lblServiceStatus.TabIndex = 1;
            lblServiceStatus.Text = "-";
            btnRefreshStatus.Location = new Point(410, 25);
            btnRefreshStatus.Name = "btnRefreshStatus";
            btnRefreshStatus.Size = new Size(140, 30);
            btnRefreshStatus.TabIndex = 2;
            btnRefreshStatus.Text = "Aktualisieren";
            btnRefreshStatus.UseVisualStyleBackColor = true;
            lblSnapshot.AutoEllipsis = true;
            lblSnapshot.BorderStyle = BorderStyle.FixedSingle;
            lblSnapshot.Location = new Point(16, 65);
            lblSnapshot.Name = "lblSnapshot";
            lblSnapshot.Size = new Size(830, 70);
            lblSnapshot.TabIndex = 3;
            lblSnapshot.Text = "Snapshot nicht geladen";
            btnTriggerCheck.Location = new Point(865, 85);
            btnTriggerCheck.Name = "btnTriggerCheck";
            btnTriggerCheck.Size = new Size(160, 30);
            btnTriggerCheck.TabIndex = 4;
            btnTriggerCheck.Text = "Check jetzt ausführen";
            btnTriggerCheck.UseVisualStyleBackColor = true;
            grpServiceActions.Controls.Add(btnInstall);
            grpServiceActions.Controls.Add(btnUninstall);
            grpServiceActions.Controls.Add(btnStart);
            grpServiceActions.Controls.Add(btnStop);
            grpServiceActions.Controls.Add(btnEventLog);
            grpServiceActions.Location = new Point(16, 185);
            grpServiceActions.Name = "grpServiceActions";
            grpServiceActions.Size = new Size(1040, 95);
            grpServiceActions.TabIndex = 1;
            grpServiceActions.TabStop = false;
            grpServiceActions.Text = "Aktionen";
            btnInstall.Location = new Point(16, 30);
            btnInstall.Name = "btnInstall";
            btnInstall.Size = new Size(140, 30);
            btnInstall.TabIndex = 0;
            btnInstall.Text = "Installieren";
            btnInstall.UseVisualStyleBackColor = true;
            btnUninstall.Location = new Point(162, 30);
            btnUninstall.Name = "btnUninstall";
            btnUninstall.Size = new Size(140, 30);
            btnUninstall.TabIndex = 1;
            btnUninstall.Text = "Deinstallieren";
            btnUninstall.UseVisualStyleBackColor = true;
            btnStart.Location = new Point(308, 30);
            btnStart.Name = "btnStart";
            btnStart.Size = new Size(140, 30);
            btnStart.TabIndex = 2;
            btnStart.Text = "Starten";
            btnStart.UseVisualStyleBackColor = true;
            btnStop.Location = new Point(454, 30);
            btnStop.Name = "btnStop";
            btnStop.Size = new Size(140, 30);
            btnStop.TabIndex = 3;
            btnStop.Text = "Stoppen";
            btnStop.UseVisualStyleBackColor = true;
            btnEventLog.Location = new Point(800, 30);
            btnEventLog.Name = "btnEventLog";
            btnEventLog.Size = new Size(220, 30);
            btnEventLog.TabIndex = 5;
            btnEventLog.Text = "Ereignisanzeige";
            btnEventLog.UseVisualStyleBackColor = true;
            tabApps.Controls.Add(grpAppsTop);
            tabApps.Controls.Add(gridApps);
            tabApps.Controls.Add(btnAddApp);
            tabApps.Controls.Add(btnRemoveApp);
            tabApps.Controls.Add(btnBrowseApp);
            tabApps.Controls.Add(grpIntervals);
            tabApps.Controls.Add(grpAppsNerd);
            tabApps.Location = new Point(4, 24);
            tabApps.Name = "tabApps";
            tabApps.Size = new Size(1092, 622);
            tabApps.TabIndex = 1;
            tabApps.Text = "Apps";
            tabApps.UseVisualStyleBackColor = true;
            grpAppsTop.Controls.Add(btnSaveApps);
            grpAppsTop.Controls.Add(btnReloadApps);
            grpAppsTop.Controls.Add(lblDirtyApps);
            grpAppsTop.Location = new Point(16, 16);
            grpAppsTop.Name = "grpAppsTop";
            grpAppsTop.Size = new Size(1040, 70);
            grpAppsTop.TabIndex = 0;
            grpAppsTop.TabStop = false;
            grpAppsTop.Text = "Konfiguration";
            btnSaveApps.Location = new Point(16, 28);
            btnSaveApps.Name = "btnSaveApps";
            btnSaveApps.Size = new Size(120, 30);
            btnSaveApps.TabIndex = 0;
            btnSaveApps.Text = "Speichern";
            btnSaveApps.UseVisualStyleBackColor = true;
            btnReloadApps.Location = new Point(144, 28);
            btnReloadApps.Name = "btnReloadApps";
            btnReloadApps.Size = new Size(120, 30);
            btnReloadApps.TabIndex = 1;
            btnReloadApps.Text = "Neu laden";
            btnReloadApps.UseVisualStyleBackColor = true;
            lblDirtyApps.Location = new Point(280, 34);
            lblDirtyApps.Name = "lblDirtyApps";
            lblDirtyApps.Size = new Size(240, 20);
            lblDirtyApps.TabIndex = 2;
            lblDirtyApps.Text = "✓ Gespeichert";
            gridApps.AllowUserToAddRows = false;
            gridApps.AllowUserToDeleteRows = false;
            gridApps.Location = new Point(16, 96);
            gridApps.Name = "gridApps";
            gridApps.RowHeadersVisible = false;
            gridApps.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            gridApps.Size = new Size(1040, 320);
            gridApps.TabIndex = 1;
            btnAddApp.Location = new Point(16, 428);
            btnAddApp.Name = "btnAddApp";
            btnAddApp.Size = new Size(120, 30);
            btnAddApp.TabIndex = 2;
            btnAddApp.Text = "Hinzufügen";
            btnAddApp.UseVisualStyleBackColor = true;
            btnRemoveApp.Location = new Point(144, 428);
            btnRemoveApp.Name = "btnRemoveApp";
            btnRemoveApp.Size = new Size(120, 30);
            btnRemoveApp.TabIndex = 3;
            btnRemoveApp.Text = "Entfernen";
            btnRemoveApp.UseVisualStyleBackColor = true;
            btnBrowseApp.Location = new Point(280, 428);
            btnBrowseApp.Name = "btnBrowseApp";
            btnBrowseApp.Size = new Size(160, 30);
            btnBrowseApp.TabIndex = 4;
            btnBrowseApp.Text = "EXE auswählen";
            btnBrowseApp.UseVisualStyleBackColor = true;
            grpIntervals.Controls.Add(lblCheckInterval);
            grpIntervals.Controls.Add(numCheckInterval);
            grpIntervals.Controls.Add(lblMailInterval);
            grpIntervals.Controls.Add(numMailInterval);
            grpIntervals.Location = new Point(16, 472);
            grpIntervals.Name = "grpIntervals";
            grpIntervals.Size = new Size(520, 90);
            grpIntervals.TabIndex = 5;
            grpIntervals.TabStop = false;
            grpIntervals.Text = "Intervalle";
            lblCheckInterval.Location = new Point(16, 30);
            lblCheckInterval.Name = "lblCheckInterval";
            lblCheckInterval.Size = new Size(200, 20);
            lblCheckInterval.TabIndex = 0;
            lblCheckInterval.Text = "Check-Intervall (Min):";
            numCheckInterval.Location = new Point(240, 28);
            numCheckInterval.Maximum = new decimal(new int[] { 1440, 0, 0, 0 });
            numCheckInterval.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
            numCheckInterval.Name = "numCheckInterval";
            numCheckInterval.Size = new Size(120, 23);
            numCheckInterval.TabIndex = 1;
            numCheckInterval.Value = new decimal(new int[] { 1, 0, 0, 0 });
            lblMailInterval.Location = new Point(16, 60);
            lblMailInterval.Name = "lblMailInterval";
            lblMailInterval.Size = new Size(200, 20);
            lblMailInterval.TabIndex = 2;
            lblMailInterval.Text = "Mail-Intervall (Std):";
            numMailInterval.Location = new Point(240, 58);
            numMailInterval.Maximum = new decimal(new int[] { 168, 0, 0, 0 });
            numMailInterval.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
            numMailInterval.Name = "numMailInterval";
            numMailInterval.Size = new Size(120, 23);
            numMailInterval.TabIndex = 3;
            numMailInterval.Value = new decimal(new int[] { 1, 0, 0, 0 });
            grpAppsNerd.Controls.Add(lblAppsNerd);
            grpAppsNerd.Location = new Point(560, 472);
            grpAppsNerd.Name = "grpAppsNerd";
            grpAppsNerd.Size = new Size(496, 90);
            grpAppsNerd.TabIndex = 6;
            grpAppsNerd.TabStop = false;
            grpAppsNerd.Text = "Nerd-Infos";
            lblAppsNerd.AutoEllipsis = true;
            lblAppsNerd.BorderStyle = BorderStyle.FixedSingle;
            lblAppsNerd.Location = new Point(16, 24);
            lblAppsNerd.Name = "lblAppsNerd";
            lblAppsNerd.Size = new Size(464, 52);
            lblAppsNerd.TabIndex = 0;
            lblAppsNerd.Text = "Apps: - | Enabled: - | LastCheck: - | NextCheck: -";
            tabMail.Controls.Add(grpMailTop);
            tabMail.Controls.Add(grpMailServer);
            tabMail.Controls.Add(grpMailAuth);
            tabMail.Controls.Add(grpMailAddresses);
            tabMail.Controls.Add(btnTestMail);
            tabMail.Controls.Add(grpMailNerd);
            tabMail.Controls.Add(grpNtfyTop);
            tabMail.Controls.Add(grpNtfyServer);
            tabMail.Controls.Add(grpNtfyAuth);
            tabMail.Controls.Add(grpNtfyMessage);
            tabMail.Controls.Add(btnTestNtfy);
            tabMail.Controls.Add(grpNtfyNerd);
            tabMail.Location = new Point(4, 24);
            tabMail.Name = "tabMail";
            tabMail.Size = new Size(1092, 622);
            tabMail.TabIndex = 2;
            tabMail.Text = "Mail / NTFY";
            tabMail.UseVisualStyleBackColor = true;
            grpMailTop.Controls.Add(btnSaveMail);
            grpMailTop.Controls.Add(btnReloadMail);
            grpMailTop.Controls.Add(lblDirtyMail);
            grpMailTop.Location = new Point(16, 16);
            grpMailTop.Name = "grpMailTop";
            grpMailTop.Size = new Size(1040, 70);
            grpMailTop.TabIndex = 0;
            grpMailTop.TabStop = false;
            grpMailTop.Text = "SMTP Konfiguration";
            btnSaveMail.Location = new Point(16, 28);
            btnSaveMail.Name = "btnSaveMail";
            btnSaveMail.Size = new Size(120, 30);
            btnSaveMail.TabIndex = 0;
            btnSaveMail.Text = "Speichern";
            btnSaveMail.UseVisualStyleBackColor = true;
            btnReloadMail.Location = new Point(144, 28);
            btnReloadMail.Name = "btnReloadMail";
            btnReloadMail.Size = new Size(120, 30);
            btnReloadMail.TabIndex = 1;
            btnReloadMail.Text = "Neu laden";
            btnReloadMail.UseVisualStyleBackColor = true;
            lblDirtyMail.Location = new Point(280, 34);
            lblDirtyMail.Name = "lblDirtyMail";
            lblDirtyMail.Size = new Size(240, 20);
            lblDirtyMail.TabIndex = 2;
            lblDirtyMail.Text = "✓ Gespeichert";
            grpMailServer.Controls.Add(lblSmtpServer);
            grpMailServer.Controls.Add(txtSmtpServer);
            grpMailServer.Controls.Add(lblSmtpPort);
            grpMailServer.Controls.Add(txtSmtpPort);
            grpMailServer.Controls.Add(chkSmtpSsl);
            grpMailServer.Location = new Point(16, 96);
            grpMailServer.Name = "grpMailServer";
            grpMailServer.Size = new Size(520, 120);
            grpMailServer.TabIndex = 1;
            grpMailServer.TabStop = false;
            grpMailServer.Text = "SMTP Server";
            lblSmtpServer.Location = new Point(16, 30);
            lblSmtpServer.Name = "lblSmtpServer";
            lblSmtpServer.Size = new Size(90, 20);
            lblSmtpServer.TabIndex = 0;
            lblSmtpServer.Text = "Server:";
            txtSmtpServer.Location = new Point(120, 28);
            txtSmtpServer.Name = "txtSmtpServer";
            txtSmtpServer.Size = new Size(380, 23);
            txtSmtpServer.TabIndex = 1;
            lblSmtpPort.Location = new Point(16, 65);
            lblSmtpPort.Name = "lblSmtpPort";
            lblSmtpPort.Size = new Size(90, 20);
            lblSmtpPort.TabIndex = 2;
            lblSmtpPort.Text = "Port:";
            txtSmtpPort.Location = new Point(120, 63);
            txtSmtpPort.Name = "txtSmtpPort";
            txtSmtpPort.Size = new Size(80, 23);
            txtSmtpPort.TabIndex = 3;
            chkSmtpSsl.Location = new Point(220, 63);
            chkSmtpSsl.Name = "chkSmtpSsl";
            chkSmtpSsl.Size = new Size(60, 23);
            chkSmtpSsl.TabIndex = 4;
            chkSmtpSsl.Text = "SSL";
            chkSmtpSsl.UseVisualStyleBackColor = true;
            grpMailAuth.Controls.Add(lblSmtpUser);
            grpMailAuth.Controls.Add(txtSmtpUser);
            grpMailAuth.Controls.Add(lblSmtpPass);
            grpMailAuth.Controls.Add(txtSmtpPass);
            grpMailAuth.Location = new Point(16, 230);
            grpMailAuth.Name = "grpMailAuth";
            grpMailAuth.Size = new Size(520, 110);
            grpMailAuth.TabIndex = 2;
            grpMailAuth.TabStop = false;
            grpMailAuth.Text = "Authentifizierung";
            lblSmtpUser.Location = new Point(16, 30);
            lblSmtpUser.Name = "lblSmtpUser";
            lblSmtpUser.Size = new Size(90, 20);
            lblSmtpUser.TabIndex = 0;
            lblSmtpUser.Text = "Benutzer:";
            txtSmtpUser.Location = new Point(120, 28);
            txtSmtpUser.Name = "txtSmtpUser";
            txtSmtpUser.Size = new Size(380, 23);
            txtSmtpUser.TabIndex = 1;
            lblSmtpPass.Location = new Point(16, 65);
            lblSmtpPass.Name = "lblSmtpPass";
            lblSmtpPass.Size = new Size(90, 20);
            lblSmtpPass.TabIndex = 2;
            lblSmtpPass.Text = "Passwort:";
            txtSmtpPass.Location = new Point(120, 63);
            txtSmtpPass.Name = "txtSmtpPass";
            txtSmtpPass.Size = new Size(380, 23);
            txtSmtpPass.TabIndex = 3;
            txtSmtpPass.UseSystemPasswordChar = true;
            grpMailAddresses.Controls.Add(lblMailFrom);
            grpMailAddresses.Controls.Add(txtMailFrom);
            grpMailAddresses.Controls.Add(lblMailTo);
            grpMailAddresses.Controls.Add(txtMailTo);
            grpMailAddresses.Location = new Point(560, 96);
            grpMailAddresses.Name = "grpMailAddresses";
            grpMailAddresses.Size = new Size(496, 120);
            grpMailAddresses.TabIndex = 3;
            grpMailAddresses.TabStop = false;
            grpMailAddresses.Text = "Adressen";
            lblMailFrom.Location = new Point(16, 30);
            lblMailFrom.Name = "lblMailFrom";
            lblMailFrom.Size = new Size(90, 20);
            lblMailFrom.TabIndex = 0;
            lblMailFrom.Text = "From:";
            txtMailFrom.Location = new Point(120, 28);
            txtMailFrom.Name = "txtMailFrom";
            txtMailFrom.Size = new Size(360, 23);
            txtMailFrom.TabIndex = 1;
            lblMailTo.Location = new Point(16, 65);
            lblMailTo.Name = "lblMailTo";
            lblMailTo.Size = new Size(90, 20);
            lblMailTo.TabIndex = 2;
            lblMailTo.Text = "To:";
            txtMailTo.Location = new Point(120, 63);
            txtMailTo.Name = "txtMailTo";
            txtMailTo.Size = new Size(360, 23);
            txtMailTo.TabIndex = 3;
            btnTestMail.Location = new Point(560, 230);
            btnTestMail.Name = "btnTestMail";
            btnTestMail.Size = new Size(200, 32);
            btnTestMail.TabIndex = 4;
            btnTestMail.Text = "Test-Mail senden";
            btnTestMail.UseVisualStyleBackColor = true;
            grpMailNerd.Controls.Add(lblMailNerd);
            grpMailNerd.Location = new Point(560, 274);
            grpMailNerd.Name = "grpMailNerd";
            grpMailNerd.Size = new Size(496, 66);
            grpMailNerd.TabIndex = 5;
            grpMailNerd.TabStop = false;
            grpMailNerd.Text = "SMTP Nerd-Infos";
            lblMailNerd.AutoEllipsis = true;
            lblMailNerd.BorderStyle = BorderStyle.FixedSingle;
            lblMailNerd.Location = new Point(16, 24);
            lblMailNerd.Name = "lblMailNerd";
            lblMailNerd.Size = new Size(464, 28);
            lblMailNerd.TabIndex = 0;
            lblMailNerd.Text = "Last Mail: - | Last Error: - | TLS: - | Auth: -";
            grpNtfyTop.Controls.Add(btnSaveNtfy);
            grpNtfyTop.Controls.Add(btnReloadNtfy);
            grpNtfyTop.Controls.Add(lblDirtyNtfy);
            grpNtfyTop.Location = new Point(16, 360);
            grpNtfyTop.Name = "grpNtfyTop";
            grpNtfyTop.Size = new Size(1040, 70);
            grpNtfyTop.TabIndex = 10;
            grpNtfyTop.TabStop = false;
            grpNtfyTop.Text = "NTFY Konfiguration";
            btnSaveNtfy.Location = new Point(16, 28);
            btnSaveNtfy.Name = "btnSaveNtfy";
            btnSaveNtfy.Size = new Size(120, 30);
            btnSaveNtfy.TabIndex = 0;
            btnSaveNtfy.Text = "Speichern";
            btnSaveNtfy.UseVisualStyleBackColor = true;
            btnReloadNtfy.Location = new Point(144, 28);
            btnReloadNtfy.Name = "btnReloadNtfy";
            btnReloadNtfy.Size = new Size(120, 30);
            btnReloadNtfy.TabIndex = 1;
            btnReloadNtfy.Text = "Neu laden";
            btnReloadNtfy.UseVisualStyleBackColor = true;
            lblDirtyNtfy.Location = new Point(280, 34);
            lblDirtyNtfy.Name = "lblDirtyNtfy";
            lblDirtyNtfy.Size = new Size(240, 20);
            lblDirtyNtfy.TabIndex = 2;
            lblDirtyNtfy.Text = "✓ Gespeichert";
            grpNtfyServer.Controls.Add(lblNtfyBaseUrl);
            grpNtfyServer.Controls.Add(txtNtfyBaseUrl);
            grpNtfyServer.Location = new Point(16, 440);
            grpNtfyServer.Name = "grpNtfyServer";
            grpNtfyServer.Size = new Size(520, 80);
            grpNtfyServer.TabIndex = 11;
            grpNtfyServer.TabStop = false;
            grpNtfyServer.Text = "NTFY Server";
            lblNtfyBaseUrl.Location = new Point(16, 32);
            lblNtfyBaseUrl.Name = "lblNtfyBaseUrl";
            lblNtfyBaseUrl.Size = new Size(90, 20);
            lblNtfyBaseUrl.TabIndex = 0;
            lblNtfyBaseUrl.Text = "Base URL:";
            txtNtfyBaseUrl.Location = new Point(120, 30);
            txtNtfyBaseUrl.Name = "txtNtfyBaseUrl";
            txtNtfyBaseUrl.Size = new Size(380, 23);
            txtNtfyBaseUrl.TabIndex = 1;
            grpNtfyAuth.Controls.Add(lblNtfyToken);
            grpNtfyAuth.Controls.Add(txtNtfyToken);
            grpNtfyAuth.Location = new Point(16, 530);
            grpNtfyAuth.Name = "grpNtfyAuth";
            grpNtfyAuth.Size = new Size(520, 80);
            grpNtfyAuth.TabIndex = 12;
            grpNtfyAuth.TabStop = false;
            grpNtfyAuth.Text = "Authentifizierung (optional)";
            lblNtfyToken.Location = new Point(16, 32);
            lblNtfyToken.Name = "lblNtfyToken";
            lblNtfyToken.Size = new Size(90, 20);
            lblNtfyToken.TabIndex = 0;
            lblNtfyToken.Text = "Token:";
            txtNtfyToken.Location = new Point(120, 30);
            txtNtfyToken.Name = "txtNtfyToken";
            txtNtfyToken.Size = new Size(380, 23);
            txtNtfyToken.TabIndex = 1;
            txtNtfyToken.UseSystemPasswordChar = true;
            grpNtfyMessage.Controls.Add(lblNtfyTopic);
            grpNtfyMessage.Controls.Add(txtNtfyTopic);
            grpNtfyMessage.Controls.Add(lblNtfyTitle);
            grpNtfyMessage.Controls.Add(txtNtfyTitle);
            grpNtfyMessage.Controls.Add(lblNtfyPriority);
            grpNtfyMessage.Controls.Add(cmbNtfyPriority);
            grpNtfyMessage.Controls.Add(lblNtfyTags);
            grpNtfyMessage.Controls.Add(txtNtfyTags);
            grpNtfyMessage.Location = new Point(560, 440);
            grpNtfyMessage.Name = "grpNtfyMessage";
            grpNtfyMessage.Size = new Size(496, 140);
            grpNtfyMessage.TabIndex = 13;
            grpNtfyMessage.TabStop = false;
            grpNtfyMessage.Text = "Nachricht / Defaults";
            lblNtfyTopic.Location = new Point(16, 30);
            lblNtfyTopic.Name = "lblNtfyTopic";
            lblNtfyTopic.Size = new Size(90, 20);
            lblNtfyTopic.TabIndex = 0;
            lblNtfyTopic.Text = "Topic:";
            txtNtfyTopic.Location = new Point(120, 28);
            txtNtfyTopic.Name = "txtNtfyTopic";
            txtNtfyTopic.Size = new Size(360, 23);
            txtNtfyTopic.TabIndex = 1;
            lblNtfyTitle.Location = new Point(16, 60);
            lblNtfyTitle.Name = "lblNtfyTitle";
            lblNtfyTitle.Size = new Size(90, 20);
            lblNtfyTitle.TabIndex = 2;
            lblNtfyTitle.Text = "Title:";
            txtNtfyTitle.Location = new Point(120, 58);
            txtNtfyTitle.Name = "txtNtfyTitle";
            txtNtfyTitle.Size = new Size(360, 23);
            txtNtfyTitle.TabIndex = 3;
            lblNtfyPriority.Location = new Point(16, 92);
            lblNtfyPriority.Name = "lblNtfyPriority";
            lblNtfyPriority.Size = new Size(90, 20);
            lblNtfyPriority.TabIndex = 4;
            lblNtfyPriority.Text = "Priority:";
            cmbNtfyPriority.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbNtfyPriority.FormattingEnabled = true;
            cmbNtfyPriority.Items.AddRange(new object[] { "min", "low", "default", "high", "max" });
            cmbNtfyPriority.Location = new Point(120, 90);
            cmbNtfyPriority.Name = "cmbNtfyPriority";
            cmbNtfyPriority.Size = new Size(120, 23);
            cmbNtfyPriority.TabIndex = 5;
            lblNtfyTags.Location = new Point(260, 92);
            lblNtfyTags.Name = "lblNtfyTags";
            lblNtfyTags.Size = new Size(50, 20);
            lblNtfyTags.TabIndex = 6;
            lblNtfyTags.Text = "Tags:";
            txtNtfyTags.Location = new Point(316, 90);
            txtNtfyTags.Name = "txtNtfyTags";
            txtNtfyTags.Size = new Size(164, 23);
            txtNtfyTags.TabIndex = 7;
            btnTestNtfy.Location = new Point(560, 590);
            btnTestNtfy.Name = "btnTestNtfy";
            btnTestNtfy.Size = new Size(200, 32);
            btnTestNtfy.TabIndex = 14;
            btnTestNtfy.Text = "Test-NTFY senden";
            btnTestNtfy.UseVisualStyleBackColor = true;
            grpNtfyNerd.Controls.Add(lblNtfyNerd);
            grpNtfyNerd.Location = new Point(776, 582);
            grpNtfyNerd.Name = "grpNtfyNerd";
            grpNtfyNerd.Size = new Size(280, 50);
            grpNtfyNerd.TabIndex = 15;
            grpNtfyNerd.TabStop = false;
            grpNtfyNerd.Text = "NTFY Nerd-Infos";
            lblNtfyNerd.AutoEllipsis = true;
            lblNtfyNerd.BorderStyle = BorderStyle.FixedSingle;
            lblNtfyNerd.Location = new Point(12, 18);
            lblNtfyNerd.Name = "lblNtfyNerd";
            lblNtfyNerd.Size = new Size(256, 22);
            lblNtfyNerd.TabIndex = 0;
            lblNtfyNerd.Text = "Last Push: - | Last HTTP: -";
            tabLogs.Controls.Add(grpLogsTop);
            tabLogs.Controls.Add(txtLogs);
            tabLogs.Controls.Add(grpLogsNerd);
            tabLogs.Location = new Point(4, 24);
            tabLogs.Name = "tabLogs";
            tabLogs.Size = new Size(1092, 622);
            tabLogs.TabIndex = 3;
            tabLogs.Text = "Logs";
            tabLogs.UseVisualStyleBackColor = true;
            grpLogsTop.Controls.Add(cmbLogDate);
            grpLogsTop.Controls.Add(btnReloadLogs);
            grpLogsTop.Controls.Add(btnOpenLogFolder);
            grpLogsTop.Controls.Add(chkAutoScroll);
            grpLogsTop.Location = new Point(16, 16);
            grpLogsTop.Name = "grpLogsTop";
            grpLogsTop.Size = new Size(1040, 70);
            grpLogsTop.TabIndex = 0;
            grpLogsTop.TabStop = false;
            grpLogsTop.Text = "Log-Auswahl (Tag-basiert)";
            cmbLogDate.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbLogDate.FormattingEnabled = true;
            cmbLogDate.Location = new Point(16, 30);
            cmbLogDate.Name = "cmbLogDate";
            cmbLogDate.Size = new Size(200, 23);
            cmbLogDate.TabIndex = 0;
            btnReloadLogs.Location = new Point(230, 27);
            btnReloadLogs.Name = "btnReloadLogs";
            btnReloadLogs.Size = new Size(140, 30);
            btnReloadLogs.TabIndex = 1;
            btnReloadLogs.Text = "Aktualisieren";
            btnReloadLogs.UseVisualStyleBackColor = true;
            btnOpenLogFolder.Location = new Point(380, 27);
            btnOpenLogFolder.Name = "btnOpenLogFolder";
            btnOpenLogFolder.Size = new Size(160, 30);
            btnOpenLogFolder.TabIndex = 2;
            btnOpenLogFolder.Text = "Log-Ordner öffnen";
            btnOpenLogFolder.UseVisualStyleBackColor = true;
            chkAutoScroll.Location = new Point(560, 31);
            chkAutoScroll.Name = "chkAutoScroll";
            chkAutoScroll.Size = new Size(200, 20);
            chkAutoScroll.TabIndex = 3;
            chkAutoScroll.Text = "Auto-Scroll";
            chkAutoScroll.UseVisualStyleBackColor = true;
            txtLogs.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            txtLogs.Font = new Font("Consolas", 9F);
            txtLogs.Location = new Point(16, 96);
            txtLogs.Name = "txtLogs";
            txtLogs.ReadOnly = true;
            txtLogs.Size = new Size(1040, 448);
            txtLogs.TabIndex = 1;
            txtLogs.Text = "";
            grpLogsNerd.Controls.Add(lblLogsNerd);
            grpLogsNerd.Location = new Point(16, 555);
            grpLogsNerd.Name = "grpLogsNerd";
            grpLogsNerd.Size = new Size(1040, 58);
            grpLogsNerd.TabIndex = 2;
            grpLogsNerd.TabStop = false;
            grpLogsNerd.Text = "Nerd-Infos";
            lblLogsNerd.AutoEllipsis = true;
            lblLogsNerd.BorderStyle = BorderStyle.FixedSingle;
            lblLogsNerd.Location = new Point(16, 22);
            lblLogsNerd.Name = "lblLogsNerd";
            lblLogsNerd.Size = new Size(1008, 26);
            lblLogsNerd.TabIndex = 0;
            lblLogsNerd.Text = "Datei: - | Größe: - | Zeilen: - | Letzter Eintrag: - | Pipe: -";
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1100, 698);
            Controls.Add(tabControl);
            Controls.Add(statusStripMain);
            Controls.Add(menuStripMain);
            MainMenuStrip = menuStripMain;
            MinimumSize = new Size(1100, 698);
            Name = "MainForm";
            Text = "AppWatchdog – Control Center";
            menuStripMain.ResumeLayout(false);
            menuStripMain.PerformLayout();
            statusStripMain.ResumeLayout(false);
            statusStripMain.PerformLayout();
            tabControl.ResumeLayout(false);
            tabService.ResumeLayout(false);
            grpServiceStatus.ResumeLayout(false);
            grpServiceActions.ResumeLayout(false);
            tabApps.ResumeLayout(false);
            grpAppsTop.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)gridApps).EndInit();
            grpIntervals.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)numCheckInterval).EndInit();
            ((System.ComponentModel.ISupportInitialize)numMailInterval).EndInit();
            grpAppsNerd.ResumeLayout(false);
            tabMail.ResumeLayout(false);
            grpMailTop.ResumeLayout(false);
            grpMailServer.ResumeLayout(false);
            grpMailServer.PerformLayout();
            grpMailAuth.ResumeLayout(false);
            grpMailAuth.PerformLayout();
            grpMailAddresses.ResumeLayout(false);
            grpMailAddresses.PerformLayout();
            grpMailNerd.ResumeLayout(false);
            grpNtfyTop.ResumeLayout(false);
            grpNtfyServer.ResumeLayout(false);
            grpNtfyServer.PerformLayout();
            grpNtfyAuth.ResumeLayout(false);
            grpNtfyAuth.PerformLayout();
            grpNtfyMessage.ResumeLayout(false);
            grpNtfyMessage.PerformLayout();
            grpNtfyNerd.ResumeLayout(false);
            tabLogs.ResumeLayout(false);
            grpLogsTop.ResumeLayout(false);
            grpLogsNerd.ResumeLayout(false);
            ResumeLayout(false);
            PerformLayout();
        }
    }
}
