//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWatchdog.Service.Notifications {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NotificationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppWatchdog.Service.Notifications.NotificationStrings", typeof(NotificationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        internal static string Error_Label {
            get {
                return ResourceManager.GetString("Error_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppWatchdog • {0} • {1}.
        /// </summary>
        internal static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart attempted.
        /// </summary>
        internal static string Restart_Attempted {
            get {
                return ResourceManager.GetString("Restart_Attempted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Reachable.
        /// </summary>
        internal static string Status_Reachable {
            get {
                return ResourceManager.GetString("Status_Reachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Unreachable.
        /// </summary>
        internal static string Status_Unreachable {
            get {
                return ResourceManager.GetString("Status_Unreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWN.
        /// </summary>
        internal static string Summary_Down {
            get {
                return ResourceManager.GetString("Summary_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESTARTED.
        /// </summary>
        internal static string Summary_Restart {
            get {
                return ResourceManager.GetString("Summary_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UP.
        /// </summary>
        internal static string Summary_Up {
            get {
                return ResourceManager.GetString("Summary_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable: {0}.
        /// </summary>
        internal static string Target_Executable {
            get {
                return ResourceManager.GetString("Target_Executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTO: {0}.
        /// </summary>
        internal static string Target_Http {
            get {
                return ResourceManager.GetString("Target_Http", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service: {0}.
        /// </summary>
        internal static string Target_Service {
            get {
                return ResourceManager.GetString("Target_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP: {0}:{1}.
        /// </summary>
        internal static string Target_Tcp {
            get {
                return ResourceManager.GetString("Target_Tcp", resourceCulture);
            }
        }
    }
}
