//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWatchdog.UI.WPF.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppWatchdog.UI.WPF.Localization.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string abort {
            get {
                return ResourceManager.GetString("abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string about_contact_email {
            get {
                return ResourceManager.GetString("about_contact_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string about_contact_github {
            get {
                return ResourceManager.GetString("about_contact_github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam.
        /// </summary>
        public static string about_contact_steam {
            get {
                return ResourceManager.GetString("about_contact_steam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images &amp; external assets.
        /// </summary>
        public static string about_external_assets {
            get {
                return ResourceManager.GetString("about_external_assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External libraries &amp; resources:.
        /// </summary>
        public static string about_external_resources_title {
            get {
                return ResourceManager.GetString("about_external_resources_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPF UI (Fluent Design Library).
        /// </summary>
        public static string about_external_wpfui {
            get {
                return ResourceManager.GetString("about_external_wpfui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status changes and errors can be sent via email to stay informed even without an active user interface..
        /// </summary>
        public static string about_feature_mail_text {
            get {
                return ResourceManager.GetString("about_feature_mail_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Email notifications.
        /// </summary>
        public static string about_feature_mail_title {
            get {
                return ResourceManager.GetString("about_feature_mail_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ntfy allows sending push notifications to mobile devices or other clients to immediately inform about relevant events..
        /// </summary>
        public static string about_feature_ntfy_text {
            get {
                return ResourceManager.GetString("about_feature_ntfy_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • ntfy (push notifications).
        /// </summary>
        public static string about_feature_ntfy_title {
            get {
                return ResourceManager.GetString("about_feature_ntfy_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration with Uptime Kuma allows embedding into existing monitoring dashboards and centralized monitoring of multiple systems..
        /// </summary>
        public static string about_feature_uptime_text {
            get {
                return ResourceManager.GetString("about_feature_uptime_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Uptime Kuma.
        /// </summary>
        public static string about_feature_uptime_title {
            get {
                return ResourceManager.GetString("about_feature_uptime_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string about_section_contact_title {
            get {
                return ResourceManager.GetString("about_section_contact_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows service.
        /// </summary>
        public static string about_section_service_title {
            get {
                return ResourceManager.GetString("about_section_service_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The actual monitoring is performed by a standalone Windows service that runs independently of the user interface in the background and regularly checks the status of the configured applications..
        /// </summary>
        public static string about_service_description_1 {
            get {
                return ResourceManager.GetString("about_service_description_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In addition to local status tracking, the service can actively report events. Various notification options are available for status changes or errors..
        /// </summary>
        public static string about_service_description_2 {
            get {
                return ResourceManager.GetString("about_service_description_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application version:.
        /// </summary>
        public static string about_version_label {
            get {
                return ResourceManager.GetString("about_version_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string apps_add {
            get {
                return ResourceManager.GetString("apps_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments (e.g. --version).
        /// </summary>
        public static string apps_arguments {
            get {
                return ResourceManager.GetString("apps_arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check interval (minutes).
        /// </summary>
        public static string apps_check_interval {
            get {
                return ResourceManager.GetString("apps_check_interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a new name for the watch job of this application..
        /// </summary>
        public static string apps_edit_job_description {
            get {
                return ResourceManager.GetString("apps_edit_job_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name helps to identify the job in the global list..
        /// </summary>
        public static string apps_edit_job_hint {
            get {
                return ResourceManager.GetString("apps_edit_job_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job name.
        /// </summary>
        public static string apps_edit_job_placeholder {
            get {
                return ResourceManager.GetString("apps_edit_job_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit job name.
        /// </summary>
        public static string apps_edit_job_title {
            get {
                return ResourceManager.GetString("apps_edit_job_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to EXE.
        /// </summary>
        public static string apps_exe_path {
            get {
                return ResourceManager.GetString("apps_exe_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General monitoring.
        /// </summary>
        public static string apps_general_monitoring {
            get {
                return ResourceManager.GetString("apps_general_monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here, the applications monitored by the watchdog are configured..
        /// </summary>
        public static string apps_hint_text {
            get {
                return ResourceManager.GetString("apps_hint_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base URL (e.g. https://url.com).
        /// </summary>
        public static string apps_kuma_base_url {
            get {
                return ResourceManager.GetString("apps_kuma_base_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Uptime Kuma.
        /// </summary>
        public static string apps_kuma_enable {
            get {
                return ResourceManager.GetString("apps_kuma_enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping interval (seconds).
        /// </summary>
        public static string apps_kuma_interval {
            get {
                return ResourceManager.GetString("apps_kuma_interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push token.
        /// </summary>
        public static string apps_kuma_token {
            get {
                return ResourceManager.GetString("apps_kuma_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail interval (hours).
        /// </summary>
        public static string apps_mail_interval {
            get {
                return ResourceManager.GetString("apps_mail_interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable monitoring.
        /// </summary>
        public static string apps_monitoring_enable {
            get {
                return ResourceManager.GetString("apps_monitoring_enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string apps_monitoring_title {
            get {
                return ResourceManager.GetString("apps_monitoring_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New application.
        /// </summary>
        public static string apps_new_application {
            get {
                return ResourceManager.GetString("apps_new_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string apps_reload {
            get {
                return ResourceManager.GetString("apps_reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string apps_remove {
            get {
                return ResourceManager.GetString("apps_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove application.
        /// </summary>
        public static string apps_remove_application {
            get {
                return ResourceManager.GetString("apps_remove_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the Watch-Job &quot;{0}&quot;?.
        /// </summary>
        public static string apps_remove_question {
            get {
                return ResourceManager.GetString("apps_remove_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to rename job..
        /// </summary>
        public static string apps_rename_hint {
            get {
                return ResourceManager.GetString("apps_rename_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select EXE.
        /// </summary>
        public static string apps_select_exe {
            get {
                return ResourceManager.GetString("apps_select_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select executable.
        /// </summary>
        public static string apps_select_executable {
            get {
                return ResourceManager.GetString("apps_select_executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable (*.exe)|*.exe|All files (*.*)|*.*.
        /// </summary>
        public static string apps_select_file_filter {
            get {
                return ResourceManager.GetString("apps_select_file_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring settings.
        /// </summary>
        public static string apps_settings_title {
            get {
                return ResourceManager.GetString("apps_settings_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        public static string apps_title {
            get {
                return ResourceManager.GetString("apps_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watched applications.
        /// </summary>
        public static string apps_watched_apps_title {
            get {
                return ResourceManager.GetString("apps_watched_apps_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config loaded..
        /// </summary>
        public static string config_loaded {
            get {
                return ResourceManager.GetString("config_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config not saved..
        /// </summary>
        public static string config_not_saved {
            get {
                return ResourceManager.GetString("config_not_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved settings, what do you want to do?.
        /// </summary>
        public static string config_not_saved_changes {
            get {
                return ResourceManager.GetString("config_not_saved_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config saved..
        /// </summary>
        public static string config_saved {
            get {
                return ResourceManager.GetString("config_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving failed.
        /// </summary>
        public static string config_saving_failed {
            get {
                return ResourceManager.GetString("config_saving_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        public static string discard {
            get {
                return ResourceManager.GetString("discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service action could not be completed..
        /// </summary>
        public static string error_service_action_failed_text {
            get {
                return ResourceManager.GetString("error_service_action_failed_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action failed.
        /// </summary>
        public static string error_service_action_failed_title {
            get {
                return ResourceManager.GetString("error_service_action_failed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        public static string error_service_dialog_showdetails {
            get {
                return ResourceManager.GetString("error_service_dialog_showdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid state.
        /// </summary>
        public static string error_service_invalid_state {
            get {
                return ResourceManager.GetString("error_service_invalid_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Watchdog service is not installed.\nDo you want to install it now?.
        /// </summary>
        public static string error_service_not_installed_text {
            get {
                return ResourceManager.GetString("error_service_not_installed_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not installed.
        /// </summary>
        public static string error_service_not_installed_title {
            get {
                return ResourceManager.GetString("error_service_not_installed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Watchdog service is installed but not running. Do you want to start it now?.
        /// </summary>
        public static string error_service_not_running_text {
            get {
                return ResourceManager.GetString("error_service_not_running_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is stopped.
        /// </summary>
        public static string error_service_not_running_title {
            get {
                return ResourceManager.GetString("error_service_not_running_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not available.
        /// </summary>
        public static string error_service_notavailable {
            get {
                return ResourceManager.GetString("error_service_notavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The watchdog service is not running or cannot be reached..
        /// </summary>
        public static string error_service_notavailable_text {
            get {
                return ResourceManager.GetString("error_service_notavailable_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string error_service_timeout {
            get {
                return ResourceManager.GetString("error_service_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Watchdog service is not responding. (timeout).
        /// </summary>
        public static string error_service_timeout_text {
            get {
                return ResourceManager.GetString("error_service_timeout_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error.
        /// </summary>
        public static string error_service_unexpected_error {
            get {
                return ResourceManager.GetString("error_service_unexpected_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service update required.
        /// </summary>
        public static string error_service_update_required {
            get {
                return ResourceManager.GetString("error_service_update_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your service is outdated and needs an update,\ndo you want to proceed with the update?.
        /// </summary>
        public static string error_service_update_required_text {
            get {
                return ResourceManager.GetString("error_service_update_required_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action was cancelled or the UAC prompt was not confirmed..
        /// </summary>
        public static string error_uac_cancelled_text {
            get {
                return ResourceManager.GetString("error_uac_cancelled_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator privileges required.
        /// </summary>
        public static string error_uac_cancelled_title {
            get {
                return ResourceManager.GetString("error_uac_cancelled_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string install {
            get {
                return ResourceManager.GetString("install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto refresh?.
        /// </summary>
        public static string logs_autorefresh {
            get {
                return ResourceManager.GetString("logs_autorefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading the log..
        /// </summary>
        public static string logs_error_while_loading {
            get {
                return ResourceManager.GetString("logs_error_while_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log from {0} - last update {1}.
        /// </summary>
        public static string logs_last_update_text {
            get {
                return ResourceManager.GetString("logs_last_update_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Day.
        /// </summary>
        public static string logs_load_day {
            get {
                return ResourceManager.GetString("logs_load_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs loaded ({0}).
        /// </summary>
        public static string logs_loaded_text {
            get {
                return ResourceManager.GetString("logs_loaded_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs loading....
        /// </summary>
        public static string logs_loading {
            get {
                return ResourceManager.GetString("logs_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No logs found..
        /// </summary>
        public static string logs_no_logs_found {
            get {
                return ResourceManager.GetString("logs_no_logs_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open logs folder.
        /// </summary>
        public static string logs_open_folder {
            get {
                return ResourceManager.GetString("logs_open_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} matches.
        /// </summary>
        public static string logs_search_matches {
            get {
                return ResourceManager.GetString("logs_search_matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search logs ....
        /// </summary>
        public static string logs_search_placeholder {
            get {
                return ResourceManager.GetString("logs_search_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string logs_title {
            get {
                return ResourceManager.GetString("logs_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Discord.
        /// </summary>
        public static string notific_discord_test {
            get {
                return ResourceManager.GetString("notific_discord_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord test successful.
        /// </summary>
        public static string notific_discord_test_success {
            get {
                return ResourceManager.GetString("notific_discord_test_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord.
        /// </summary>
        public static string notific_discord_title {
            get {
                return ResourceManager.GetString("notific_discord_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayname.
        /// </summary>
        public static string notific_discord_username {
            get {
                return ResourceManager.GetString("notific_discord_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webhook URL.
        /// </summary>
        public static string notific_discord_webhook {
            get {
                return ResourceManager.GetString("notific_discord_webhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string notific_enabled {
            get {
                return ResourceManager.GetString("notific_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base URL.
        /// </summary>
        public static string notific_ntfy_base_url {
            get {
                return ResourceManager.GetString("notific_ntfy_base_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string notific_ntfy_enabled {
            get {
                return ResourceManager.GetString("notific_ntfy_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority (1–5).
        /// </summary>
        public static string notific_ntfy_priority {
            get {
                return ResourceManager.GetString("notific_ntfy_priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTFY-Test successful.
        /// </summary>
        public static string notific_ntfy_successful {
            get {
                return ResourceManager.GetString("notific_ntfy_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTFY-Test.
        /// </summary>
        public static string notific_ntfy_test {
            get {
                return ResourceManager.GetString("notific_ntfy_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTFY-Test failed.
        /// </summary>
        public static string notific_ntfy_test_failed {
            get {
                return ResourceManager.GetString("notific_ntfy_test_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTFY-Test successfully finished..
        /// </summary>
        public static string notific_ntfy_test_success_finish {
            get {
                return ResourceManager.GetString("notific_ntfy_test_success_finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTFY.
        /// </summary>
        public static string notific_ntfy_title {
            get {
                return ResourceManager.GetString("notific_ntfy_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTFY token.
        /// </summary>
        public static string notific_ntfy_token {
            get {
                return ResourceManager.GetString("notific_ntfy_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        public static string notific_ntfy_topic {
            get {
                return ResourceManager.GetString("notific_ntfy_topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender (From).
        /// </summary>
        public static string notific_smtp_from {
            get {
                return ResourceManager.GetString("notific_smtp_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP password.
        /// </summary>
        public static string notific_smtp_password {
            get {
                return ResourceManager.GetString("notific_smtp_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string notific_smtp_port {
            get {
                return ResourceManager.GetString("notific_smtp_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string notific_smtp_server {
            get {
                return ResourceManager.GetString("notific_smtp_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable SSL.
        /// </summary>
        public static string notific_smtp_ssl {
            get {
                return ResourceManager.GetString("notific_smtp_ssl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP-Test.
        /// </summary>
        public static string notific_smtp_test {
            get {
                return ResourceManager.GetString("notific_smtp_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP-Test failed.
        /// </summary>
        public static string notific_smtp_test_failed {
            get {
                return ResourceManager.GetString("notific_smtp_test_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP-Test successful.
        /// </summary>
        public static string notific_smtp_test_success {
            get {
                return ResourceManager.GetString("notific_smtp_test_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP-Test successfully completed..
        /// </summary>
        public static string notific_smtp_test_success_finish {
            get {
                return ResourceManager.GetString("notific_smtp_test_success_finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string notific_smtp_title {
            get {
                return ResourceManager.GetString("notific_smtp_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient (To).
        /// </summary>
        public static string notific_smtp_to {
            get {
                return ResourceManager.GetString("notific_smtp_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string notific_smtp_user {
            get {
                return ResourceManager.GetString("notific_smtp_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot token.
        /// </summary>
        public static string notific_telegram_bot_token {
            get {
                return ResourceManager.GetString("notific_telegram_bot_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat ID.
        /// </summary>
        public static string notific_telegram_chat_id {
            get {
                return ResourceManager.GetString("notific_telegram_chat_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Telegram.
        /// </summary>
        public static string notific_telegram_test {
            get {
                return ResourceManager.GetString("notific_telegram_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram test successful.
        /// </summary>
        public static string notific_telegram_test_success {
            get {
                return ResourceManager.GetString("notific_telegram_test_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram.
        /// </summary>
        public static string notific_telegram_title {
            get {
                return ResourceManager.GetString("notific_telegram_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure notification channels for AppWatchdog. SMTP is used for email notifications, NTFY for push notifications..
        /// </summary>
        public static string notifications_description {
            get {
                return ResourceManager.GetString("notifications_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string notifications_header {
            get {
                return ResourceManager.GetString("notifications_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string notifications_title {
            get {
                return ResourceManager.GetString("notifications_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe is not available ({0}).
        /// </summary>
        public static string pipe_not_available_ex {
            get {
                return ResourceManager.GetString("pipe_not_available_ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstall.
        /// </summary>
        public static string reinstall {
            get {
                return ResourceManager.GetString("reinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing action ....
        /// </summary>
        public static string service_action_in_progress {
            get {
                return ResourceManager.GetString("service_action_in_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action was completed successfully..
        /// </summary>
        public static string service_action_success_text {
            get {
                return ResourceManager.GetString("service_action_success_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string service_action_success_title {
            get {
                return ResourceManager.GetString("service_action_success_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active applications.
        /// </summary>
        public static string service_active_apps_title {
            get {
                return ResourceManager.GetString("service_active_apps_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active: {0}.
        /// </summary>
        public static string service_app_active {
            get {
                return ResourceManager.GetString("service_app_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string service_button_install {
            get {
                return ResourceManager.GetString("service_button_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string service_button_start {
            get {
                return ResourceManager.GetString("service_button_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string service_button_stop {
            get {
                return ResourceManager.GetString("service_button_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string service_button_uninstall {
            get {
                return ResourceManager.GetString("service_button_uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service connected.
        /// </summary>
        public static string service_connected {
            get {
                return ResourceManager.GetString("service_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status, system information and currently monitored applications of the AppWatchdog service..
        /// </summary>
        public static string service_description {
            get {
                return ResourceManager.GetString("service_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET version:.
        /// </summary>
        public static string service_dotnet {
            get {
                return ResourceManager.GetString("service_dotnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service error.
        /// </summary>
        public static string service_error {
            get {
                return ResourceManager.GetString("service_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine name:.
        /// </summary>
        public static string service_machine_name {
            get {
                return ResourceManager.GetString("service_machine_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory:.
        /// </summary>
        public static string service_memory {
            get {
                return ResourceManager.GetString("service_memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active applications..
        /// </summary>
        public static string service_no_active_apps {
            get {
                return ResourceManager.GetString("service_no_active_apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating system:.
        /// </summary>
        public static string service_os {
            get {
                return ResourceManager.GetString("service_os", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PipeProtocol (Client):.
        /// </summary>
        public static string service_pipe_client {
            get {
                return ResourceManager.GetString("service_pipe_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PipeProtocol (Service):.
        /// </summary>
        public static string service_pipe_service {
            get {
                return ResourceManager.GetString("service_pipe_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service stopped.
        /// </summary>
        public static string service_stopped {
            get {
                return ResourceManager.GetString("service_stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service successfully installed.
        /// </summary>
        public static string service_succesfully_installed {
            get {
                return ResourceManager.GetString("service_succesfully_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service successfully started.
        /// </summary>
        public static string service_succesfully_started {
            get {
                return ResourceManager.GetString("service_succesfully_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service successfully stopped.
        /// </summary>
        public static string service_succesfully_stopped {
            get {
                return ResourceManager.GetString("service_succesfully_stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service successfully uninstalled.
        /// </summary>
        public static string service_succesfully_uninstalled {
            get {
                return ResourceManager.GetString("service_succesfully_uninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} MB free / {1} MB total.
        /// </summary>
        public static string service_system_info_memory {
            get {
                return ResourceManager.GetString("service_system_info_memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System information.
        /// </summary>
        public static string service_systeminfo_title {
            get {
                return ResourceManager.GetString("service_systeminfo_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string service_title {
            get {
                return ResourceManager.GetString("service_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service uptime:.
        /// </summary>
        public static string service_uptime {
            get {
                return ResourceManager.GetString("service_uptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string service_username {
            get {
                return ResourceManager.GetString("service_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string warn {
            get {
                return ResourceManager.GetString("warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
